# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"k\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1d\n\x05genre\x18\x04 \x01(\x0e\x32\x0e.library.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"\x14\n\x04ISBN\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"v\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x1d\n\x04\x62ook\x18\x02 \x01(\x0b\x32\r.library.BookH\x00\x12\x1f\n\x06status\x18\x03 \x01(\x0e\x32\x0f.library.StatusB\x0b\n\trefers_to*I\n\x05Genre\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06HORROR\x10\x01\x12\x0c\n\x08THRILLER\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03\x12\x08\n\x04KIDS\x10\x04*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32`\n\tInventory\x12*\n\nCreateBook\x12\r.library.Book\x1a\r.library.ISBN\x12\'\n\x07GetBook\x12\r.library.ISBN\x1a\r.library.Bookb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=277
  _GENRE._serialized_end=350
  _STATUS._serialized_start=352
  _STATUS._serialized_end=386
  _BOOK._serialized_start=26
  _BOOK._serialized_end=133
  _ISBN._serialized_start=135
  _ISBN._serialized_end=155
  _INVENTORYITEM._serialized_start=157
  _INVENTORYITEM._serialized_end=275
  _INVENTORY._serialized_start=388
  _INVENTORY._serialized_end=484
# @@protoc_insertion_point(module_scope)
